baseURL = 'https://yami02.github.io/CTF_HTB/'
languageCode = 'pt-br'
title = '0xYami02'
theme = 'cyberpunk'
ignoreFiles = ['^README\.md$']
paginate = 10

[params]
  description = "Writeups & CTF Hacking Notes — 0xNihil"
  author = "0xYami02"
  handle = "0xNihil"
  tagline = "nihil.exec();"
  github = "https://github.com/Yami02"
  htb_profile = "https://www.hackthebox.com"
  linkedin = "https://www.linkedin.com/in/adalberto-nobre-neto/"
  showReadingTime = true

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]
